/**
 * Cost API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AllocationProperties model module.
 * @module model/AllocationProperties
 * @version 2.0.0
 */
class AllocationProperties {
    /**
     * Constructs a new <code>AllocationProperties</code>.
     * @alias module:model/AllocationProperties
     */
    constructor() { 
        
        AllocationProperties.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AllocationProperties</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AllocationProperties} obj Optional instance to populate.
     * @return {module:model/AllocationProperties} The populated <code>AllocationProperties</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AllocationProperties();

            if (data.hasOwnProperty('cluster')) {
                obj['cluster'] = ApiClient.convertToType(data['cluster'], 'String');
            }
            if (data.hasOwnProperty('node')) {
                obj['node'] = ApiClient.convertToType(data['node'], 'String');
            }
            if (data.hasOwnProperty('controller')) {
                obj['controller'] = ApiClient.convertToType(data['controller'], 'String');
            }
            if (data.hasOwnProperty('controllerKind')) {
                obj['controllerKind'] = ApiClient.convertToType(data['controllerKind'], 'String');
            }
            if (data.hasOwnProperty('namespace')) {
                obj['namespace'] = ApiClient.convertToType(data['namespace'], 'String');
            }
            if (data.hasOwnProperty('pod')) {
                obj['pod'] = ApiClient.convertToType(data['pod'], 'String');
            }
            if (data.hasOwnProperty('labels')) {
                obj['labels'] = ApiClient.convertToType(data['labels'], {'String': 'String'});
            }
            if (data.hasOwnProperty('providerID')) {
                obj['providerID'] = ApiClient.convertToType(data['providerID'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AllocationProperties</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AllocationProperties</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['cluster'] && !(typeof data['cluster'] === 'string' || data['cluster'] instanceof String)) {
            throw new Error("Expected the field `cluster` to be a primitive type in the JSON string but got " + data['cluster']);
        }
        // ensure the json data is a string
        if (data['node'] && !(typeof data['node'] === 'string' || data['node'] instanceof String)) {
            throw new Error("Expected the field `node` to be a primitive type in the JSON string but got " + data['node']);
        }
        // ensure the json data is a string
        if (data['controller'] && !(typeof data['controller'] === 'string' || data['controller'] instanceof String)) {
            throw new Error("Expected the field `controller` to be a primitive type in the JSON string but got " + data['controller']);
        }
        // ensure the json data is a string
        if (data['controllerKind'] && !(typeof data['controllerKind'] === 'string' || data['controllerKind'] instanceof String)) {
            throw new Error("Expected the field `controllerKind` to be a primitive type in the JSON string but got " + data['controllerKind']);
        }
        // ensure the json data is a string
        if (data['namespace'] && !(typeof data['namespace'] === 'string' || data['namespace'] instanceof String)) {
            throw new Error("Expected the field `namespace` to be a primitive type in the JSON string but got " + data['namespace']);
        }
        // ensure the json data is a string
        if (data['pod'] && !(typeof data['pod'] === 'string' || data['pod'] instanceof String)) {
            throw new Error("Expected the field `pod` to be a primitive type in the JSON string but got " + data['pod']);
        }
        // ensure the json data is a string
        if (data['providerID'] && !(typeof data['providerID'] === 'string' || data['providerID'] instanceof String)) {
            throw new Error("Expected the field `providerID` to be a primitive type in the JSON string but got " + data['providerID']);
        }

        return true;
    }


}



/**
 * @member {String} cluster
 */
AllocationProperties.prototype['cluster'] = undefined;

/**
 * @member {String} node
 */
AllocationProperties.prototype['node'] = undefined;

/**
 * @member {String} controller
 */
AllocationProperties.prototype['controller'] = undefined;

/**
 * @member {String} controllerKind
 */
AllocationProperties.prototype['controllerKind'] = undefined;

/**
 * @member {String} namespace
 */
AllocationProperties.prototype['namespace'] = undefined;

/**
 * @member {String} pod
 */
AllocationProperties.prototype['pod'] = undefined;

/**
 * @member {Object.<String, String>} labels
 */
AllocationProperties.prototype['labels'] = undefined;

/**
 * @member {String} providerID
 */
AllocationProperties.prototype['providerID'] = undefined;






export default AllocationProperties;

