/**
 * Cost API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AllocationProperties from './AllocationProperties';

/**
 * The Allocation model module.
 * @module model/Allocation
 * @version 2.0.0
 */
class Allocation {
    /**
     * Constructs a new <code>Allocation</code>.
     * @alias module:model/Allocation
     */
    constructor() { 
        
        Allocation.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Allocation</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Allocation} obj Optional instance to populate.
     * @return {module:model/Allocation} The populated <code>Allocation</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Allocation();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('properties')) {
                obj['properties'] = AllocationProperties.constructFromObject(data['properties']);
            }
            if (data.hasOwnProperty('start')) {
                obj['start'] = ApiClient.convertToType(data['start'], 'Date');
            }
            if (data.hasOwnProperty('end')) {
                obj['end'] = ApiClient.convertToType(data['end'], 'Date');
            }
            if (data.hasOwnProperty('cpuCoreRequestAverage')) {
                obj['cpuCoreRequestAverage'] = ApiClient.convertToType(data['cpuCoreRequestAverage'], 'Number');
            }
            if (data.hasOwnProperty('cpuCoreUsageAverage')) {
                obj['cpuCoreUsageAverage'] = ApiClient.convertToType(data['cpuCoreUsageAverage'], 'Number');
            }
            if (data.hasOwnProperty('ramByteRequestAverage')) {
                obj['ramByteRequestAverage'] = ApiClient.convertToType(data['ramByteRequestAverage'], 'Number');
            }
            if (data.hasOwnProperty('ramByteUsageAverage')) {
                obj['ramByteUsageAverage'] = ApiClient.convertToType(data['ramByteUsageAverage'], 'Number');
            }
            if (data.hasOwnProperty('cost')) {
                obj['cost'] = ApiClient.convertToType(data['cost'], 'Number');
            }
            if (data.hasOwnProperty('costRatio')) {
                obj['costRatio'] = ApiClient.convertToType(data['costRatio'], 'Number');
            }
            if (data.hasOwnProperty('customCost')) {
                obj['customCost'] = ApiClient.convertToType(data['customCost'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Allocation</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Allocation</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // validate the optional field `properties`
        if (data['properties']) { // data not null
          AllocationProperties.validateJSON(data['properties']);
        }

        return true;
    }


}



/**
 * @member {String} name
 */
Allocation.prototype['name'] = undefined;

/**
 * @member {module:model/AllocationProperties} properties
 */
Allocation.prototype['properties'] = undefined;

/**
 * @member {Date} start
 */
Allocation.prototype['start'] = undefined;

/**
 * @member {Date} end
 */
Allocation.prototype['end'] = undefined;

/**
 * @member {Number} cpuCoreRequestAverage
 */
Allocation.prototype['cpuCoreRequestAverage'] = undefined;

/**
 * @member {Number} cpuCoreUsageAverage
 */
Allocation.prototype['cpuCoreUsageAverage'] = undefined;

/**
 * @member {Number} ramByteRequestAverage
 */
Allocation.prototype['ramByteRequestAverage'] = undefined;

/**
 * @member {Number} ramByteUsageAverage
 */
Allocation.prototype['ramByteUsageAverage'] = undefined;

/**
 * @member {Number} cost
 */
Allocation.prototype['cost'] = undefined;

/**
 * @member {Number} costRatio
 */
Allocation.prototype['costRatio'] = undefined;

/**
 * @member {Number} customCost
 */
Allocation.prototype['customCost'] = undefined;






export default Allocation;

