/**
 * Cost API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import Allocation from './model/Allocation';
import AllocationProperties from './model/AllocationProperties';
import AllocationSetRange from './model/AllocationSetRange';
import DefaultApi from './api/DefaultApi';
import { KubeConfigAuth, loadKubeConfig, extractAuthFromKubeconfig } from './kubeconfig.js';


/**
* JS API client generated by OpenAPI Generator.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var CostApi = require('index'); // See note below*.
* var xxxSvc = new CostApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new CostApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new CostApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new CostApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 2.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Allocation model constructor.
     * @property {module:model/Allocation}
     */
    Allocation,

    /**
     * The AllocationProperties model constructor.
     * @property {module:model/AllocationProperties}
     */
    AllocationProperties,

    /**
     * The AllocationSetRange model constructor.
     * @property {module:model/AllocationSetRange}
     */
    AllocationSetRange,

    /**
    * The DefaultApi service constructor.
    * @property {module:api/DefaultApi}
    */
    DefaultApi,

    /**
     * Kubeconfig support classes and functions
     * @property {module:kubeconfig}
     */
    KubeConfigAuth,
    loadKubeConfig,
    extractAuthFromKubeconfig
};
