# coding: utf-8

"""
    Cost API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class AllocationProperties(BaseModel):
    """
    AllocationProperties
    """ # noqa: E501
    cluster: Optional[StrictStr] = None
    node: Optional[StrictStr] = None
    controller: Optional[StrictStr] = None
    controller_kind: Optional[StrictStr] = Field(default=None, alias="controllerKind")
    namespace: Optional[StrictStr] = None
    pod: Optional[StrictStr] = None
    labels: Optional[Dict[str, StrictStr]] = None
    provider_id: Optional[StrictStr] = Field(default=None, alias="providerID")
    __properties: ClassVar[List[str]] = ["cluster", "node", "controller", "controllerKind", "namespace", "pod", "labels", "providerID"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AllocationProperties from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AllocationProperties from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "cluster": obj.get("cluster"),
            "node": obj.get("node"),
            "controller": obj.get("controller"),
            "controllerKind": obj.get("controllerKind"),
            "namespace": obj.get("namespace"),
            "pod": obj.get("pod"),
            "labels": obj.get("labels"),
            "providerID": obj.get("providerID")
        })
        return _obj


