/**
 * Cost API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import AllocationSetRange from '../model/AllocationSetRange';

/**
* Default service.
* @module api/DefaultApi
* @version 2.0.0
*/
export default class DefaultApi {

    /**
    * Constructs a new DefaultApi. 
    * @alias module:api/DefaultApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getAllocation operation.
     * @callback module:api/DefaultApi~getAllocationCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AllocationSetRange} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Compute allocation
     * @param {String} window The time range to be queried.
     * @param {Object} opts Optional parameters
     * @param {String} [filter] The filter options for workloads.
     * @param {String} [step] The interval that is used to split the time range.
     * @param {module:model/String} [aggregate] The aggregate options for the returned results from different dimensions.
     * @param {Boolean} [idle = true)] Specifies whether to display or process idle costs.
     * @param {Boolean} [shareIdle = false)] Specifies whether to allocate idle costs to each resource.
     * @param {module:model/String} [shareSplit = 'weighted')] The idle cost allocation policy.
     * @param {Boolean} [idleByNode = false)] Specifies whether to aggregate idle costs of each node. This parameter takes effect only if you set the aggregate parameter to node and the shareIdle parameter to false.
     * @param {module:model/String} [format = 'json')] The format that is used to export costs.
     * @param {module:api/DefaultApi~getAllocationCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/AllocationSetRange}
     */
    getAllocation(window, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'window' is set
      if (window === undefined || window === null) {
        throw new Error("Missing the required parameter 'window' when calling getAllocation");
      }

      let pathParams = {
      };
      let queryParams = {
        'window': window,
        'filter': opts['filter'],
        'step': opts['step'],
        'aggregate': opts['aggregate'],
        'idle': opts['idle'],
        'shareIdle': opts['shareIdle'],
        'shareSplit': opts['shareSplit'],
        'idleByNode': opts['idleByNode'],
        'format': opts['format']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = AllocationSetRange;
      return this.apiClient.callApi(
        '/v2/allocation', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getCost operation.
     * @callback module:api/DefaultApi~getCostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AllocationSetRange} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get estimated cost
     * @param {String} window The time range to be queried.
     * @param {Object} opts Optional parameters
     * @param {String} [filter] The filter options for workloads.
     * @param {String} [step] The interval that is used to split the time range.
     * @param {module:model/String} [aggregate] The aggregate options for the returned results from different dimensions.
     * @param {Boolean} [idle = true)] Specifies whether to display or process idle costs.
     * @param {Boolean} [shareIdle = false)] Specifies whether to allocate idle costs to each resource.
     * @param {module:model/String} [shareSplit = 'weighted')] The idle cost allocation policy.
     * @param {Boolean} [idleByNode = false)] Specifies whether to aggregate idle costs of each node. This parameter takes effect only if you set the aggregate parameter to node and the shareIdle parameter to false.
     * @param {module:model/String} [format = 'json')] The format that is used to export costs.
     * @param {module:api/DefaultApi~getCostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/AllocationSetRange}
     */
    getCost(window, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'window' is set
      if (window === undefined || window === null) {
        throw new Error("Missing the required parameter 'window' when calling getCost");
      }

      let pathParams = {
      };
      let queryParams = {
        'window': window,
        'filter': opts['filter'],
        'step': opts['step'],
        'aggregate': opts['aggregate'],
        'idle': opts['idle'],
        'shareIdle': opts['shareIdle'],
        'shareSplit': opts['shareSplit'],
        'idleByNode': opts['idleByNode'],
        'format': opts['format']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = AllocationSetRange;
      return this.apiClient.callApi(
        '/v2/cost', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
