/*
 * Cost API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.client.model.AllocationProperties;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import org.openapitools.client.JSON;

/**
 * Allocation
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-10-15T18:44:41.522481+08:00[Asia/Shanghai]", comments = "Generator version: 7.16.0")
public class Allocation {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nullable
  private String name;

  public static final String SERIALIZED_NAME_PROPERTIES = "properties";
  @SerializedName(SERIALIZED_NAME_PROPERTIES)
  @javax.annotation.Nullable
  private AllocationProperties properties;

  public static final String SERIALIZED_NAME_START = "start";
  @SerializedName(SERIALIZED_NAME_START)
  @javax.annotation.Nullable
  private OffsetDateTime start;

  public static final String SERIALIZED_NAME_END = "end";
  @SerializedName(SERIALIZED_NAME_END)
  @javax.annotation.Nullable
  private OffsetDateTime end;

  public static final String SERIALIZED_NAME_CPU_CORE_REQUEST_AVERAGE = "cpuCoreRequestAverage";
  @SerializedName(SERIALIZED_NAME_CPU_CORE_REQUEST_AVERAGE)
  @javax.annotation.Nullable
  private Float cpuCoreRequestAverage;

  public static final String SERIALIZED_NAME_CPU_CORE_USAGE_AVERAGE = "cpuCoreUsageAverage";
  @SerializedName(SERIALIZED_NAME_CPU_CORE_USAGE_AVERAGE)
  @javax.annotation.Nullable
  private Float cpuCoreUsageAverage;

  public static final String SERIALIZED_NAME_RAM_BYTE_REQUEST_AVERAGE = "ramByteRequestAverage";
  @SerializedName(SERIALIZED_NAME_RAM_BYTE_REQUEST_AVERAGE)
  @javax.annotation.Nullable
  private Float ramByteRequestAverage;

  public static final String SERIALIZED_NAME_RAM_BYTE_USAGE_AVERAGE = "ramByteUsageAverage";
  @SerializedName(SERIALIZED_NAME_RAM_BYTE_USAGE_AVERAGE)
  @javax.annotation.Nullable
  private Float ramByteUsageAverage;

  public static final String SERIALIZED_NAME_COST = "cost";
  @SerializedName(SERIALIZED_NAME_COST)
  @javax.annotation.Nullable
  private Float cost;

  public static final String SERIALIZED_NAME_COST_RATIO = "costRatio";
  @SerializedName(SERIALIZED_NAME_COST_RATIO)
  @javax.annotation.Nullable
  private Float costRatio;

  public static final String SERIALIZED_NAME_CUSTOM_COST = "customCost";
  @SerializedName(SERIALIZED_NAME_CUSTOM_COST)
  @javax.annotation.Nullable
  private Float customCost;

  public Allocation() {
  }

  public Allocation name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public Allocation properties(@javax.annotation.Nullable AllocationProperties properties) {
    this.properties = properties;
    return this;
  }

  /**
   * Get properties
   * @return properties
   */
  @javax.annotation.Nullable
  public AllocationProperties getProperties() {
    return properties;
  }

  public void setProperties(@javax.annotation.Nullable AllocationProperties properties) {
    this.properties = properties;
  }


  public Allocation start(@javax.annotation.Nullable OffsetDateTime start) {
    this.start = start;
    return this;
  }

  /**
   * Get start
   * @return start
   */
  @javax.annotation.Nullable
  public OffsetDateTime getStart() {
    return start;
  }

  public void setStart(@javax.annotation.Nullable OffsetDateTime start) {
    this.start = start;
  }


  public Allocation end(@javax.annotation.Nullable OffsetDateTime end) {
    this.end = end;
    return this;
  }

  /**
   * Get end
   * @return end
   */
  @javax.annotation.Nullable
  public OffsetDateTime getEnd() {
    return end;
  }

  public void setEnd(@javax.annotation.Nullable OffsetDateTime end) {
    this.end = end;
  }


  public Allocation cpuCoreRequestAverage(@javax.annotation.Nullable Float cpuCoreRequestAverage) {
    this.cpuCoreRequestAverage = cpuCoreRequestAverage;
    return this;
  }

  /**
   * Get cpuCoreRequestAverage
   * @return cpuCoreRequestAverage
   */
  @javax.annotation.Nullable
  public Float getCpuCoreRequestAverage() {
    return cpuCoreRequestAverage;
  }

  public void setCpuCoreRequestAverage(@javax.annotation.Nullable Float cpuCoreRequestAverage) {
    this.cpuCoreRequestAverage = cpuCoreRequestAverage;
  }


  public Allocation cpuCoreUsageAverage(@javax.annotation.Nullable Float cpuCoreUsageAverage) {
    this.cpuCoreUsageAverage = cpuCoreUsageAverage;
    return this;
  }

  /**
   * Get cpuCoreUsageAverage
   * @return cpuCoreUsageAverage
   */
  @javax.annotation.Nullable
  public Float getCpuCoreUsageAverage() {
    return cpuCoreUsageAverage;
  }

  public void setCpuCoreUsageAverage(@javax.annotation.Nullable Float cpuCoreUsageAverage) {
    this.cpuCoreUsageAverage = cpuCoreUsageAverage;
  }


  public Allocation ramByteRequestAverage(@javax.annotation.Nullable Float ramByteRequestAverage) {
    this.ramByteRequestAverage = ramByteRequestAverage;
    return this;
  }

  /**
   * Get ramByteRequestAverage
   * @return ramByteRequestAverage
   */
  @javax.annotation.Nullable
  public Float getRamByteRequestAverage() {
    return ramByteRequestAverage;
  }

  public void setRamByteRequestAverage(@javax.annotation.Nullable Float ramByteRequestAverage) {
    this.ramByteRequestAverage = ramByteRequestAverage;
  }


  public Allocation ramByteUsageAverage(@javax.annotation.Nullable Float ramByteUsageAverage) {
    this.ramByteUsageAverage = ramByteUsageAverage;
    return this;
  }

  /**
   * Get ramByteUsageAverage
   * @return ramByteUsageAverage
   */
  @javax.annotation.Nullable
  public Float getRamByteUsageAverage() {
    return ramByteUsageAverage;
  }

  public void setRamByteUsageAverage(@javax.annotation.Nullable Float ramByteUsageAverage) {
    this.ramByteUsageAverage = ramByteUsageAverage;
  }


  public Allocation cost(@javax.annotation.Nullable Float cost) {
    this.cost = cost;
    return this;
  }

  /**
   * Get cost
   * @return cost
   */
  @javax.annotation.Nullable
  public Float getCost() {
    return cost;
  }

  public void setCost(@javax.annotation.Nullable Float cost) {
    this.cost = cost;
  }


  public Allocation costRatio(@javax.annotation.Nullable Float costRatio) {
    this.costRatio = costRatio;
    return this;
  }

  /**
   * Get costRatio
   * @return costRatio
   */
  @javax.annotation.Nullable
  public Float getCostRatio() {
    return costRatio;
  }

  public void setCostRatio(@javax.annotation.Nullable Float costRatio) {
    this.costRatio = costRatio;
  }


  public Allocation customCost(@javax.annotation.Nullable Float customCost) {
    this.customCost = customCost;
    return this;
  }

  /**
   * Get customCost
   * @return customCost
   */
  @javax.annotation.Nullable
  public Float getCustomCost() {
    return customCost;
  }

  public void setCustomCost(@javax.annotation.Nullable Float customCost) {
    this.customCost = customCost;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Allocation allocation = (Allocation) o;
    return Objects.equals(this.name, allocation.name) &&
        Objects.equals(this.properties, allocation.properties) &&
        Objects.equals(this.start, allocation.start) &&
        Objects.equals(this.end, allocation.end) &&
        Objects.equals(this.cpuCoreRequestAverage, allocation.cpuCoreRequestAverage) &&
        Objects.equals(this.cpuCoreUsageAverage, allocation.cpuCoreUsageAverage) &&
        Objects.equals(this.ramByteRequestAverage, allocation.ramByteRequestAverage) &&
        Objects.equals(this.ramByteUsageAverage, allocation.ramByteUsageAverage) &&
        Objects.equals(this.cost, allocation.cost) &&
        Objects.equals(this.costRatio, allocation.costRatio) &&
        Objects.equals(this.customCost, allocation.customCost);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, properties, start, end, cpuCoreRequestAverage, cpuCoreUsageAverage, ramByteRequestAverage, ramByteUsageAverage, cost, costRatio, customCost);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Allocation {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
    sb.append("    start: ").append(toIndentedString(start)).append("\n");
    sb.append("    end: ").append(toIndentedString(end)).append("\n");
    sb.append("    cpuCoreRequestAverage: ").append(toIndentedString(cpuCoreRequestAverage)).append("\n");
    sb.append("    cpuCoreUsageAverage: ").append(toIndentedString(cpuCoreUsageAverage)).append("\n");
    sb.append("    ramByteRequestAverage: ").append(toIndentedString(ramByteRequestAverage)).append("\n");
    sb.append("    ramByteUsageAverage: ").append(toIndentedString(ramByteUsageAverage)).append("\n");
    sb.append("    cost: ").append(toIndentedString(cost)).append("\n");
    sb.append("    costRatio: ").append(toIndentedString(costRatio)).append("\n");
    sb.append("    customCost: ").append(toIndentedString(customCost)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("name", "properties", "start", "end", "cpuCoreRequestAverage", "cpuCoreUsageAverage", "ramByteRequestAverage", "ramByteUsageAverage", "cost", "costRatio", "customCost"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Allocation
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Allocation.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in Allocation is not found in the empty JSON string", Allocation.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Allocation.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `Allocation` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      // validate the optional field `properties`
      if (jsonObj.get("properties") != null && !jsonObj.get("properties").isJsonNull()) {
        AllocationProperties.validateJsonElement(jsonObj.get("properties"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Allocation.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Allocation' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Allocation> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Allocation.class));

       return (TypeAdapter<T>) new TypeAdapter<Allocation>() {
           @Override
           public void write(JsonWriter out, Allocation value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Allocation read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Allocation given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Allocation
   * @throws IOException if the JSON string is invalid with respect to Allocation
   */
  public static Allocation fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Allocation.class);
  }

  /**
   * Convert an instance of Allocation to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

