/*
Cost API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the AllocationProperties type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AllocationProperties{}

// AllocationProperties struct for AllocationProperties
type AllocationProperties struct {
	Cluster        *string            `json:"cluster,omitempty"`
	Node           *string            `json:"node,omitempty"`
	Controller     *string            `json:"controller,omitempty"`
	ControllerKind *string            `json:"controllerKind,omitempty"`
	Namespace      *string            `json:"namespace,omitempty"`
	Pod            *string            `json:"pod,omitempty"`
	Labels         *map[string]string `json:"labels,omitempty"`
	ProviderID     *string            `json:"providerID,omitempty"`
}

// NewAllocationProperties instantiates a new AllocationProperties object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAllocationProperties() *AllocationProperties {
	this := AllocationProperties{}
	return &this
}

// NewAllocationPropertiesWithDefaults instantiates a new AllocationProperties object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAllocationPropertiesWithDefaults() *AllocationProperties {
	this := AllocationProperties{}
	return &this
}

// GetCluster returns the Cluster field value if set, zero value otherwise.
func (o *AllocationProperties) GetCluster() string {
	if o == nil || IsNil(o.Cluster) {
		var ret string
		return ret
	}
	return *o.Cluster
}

// GetClusterOk returns a tuple with the Cluster field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AllocationProperties) GetClusterOk() (*string, bool) {
	if o == nil || IsNil(o.Cluster) {
		return nil, false
	}
	return o.Cluster, true
}

// HasCluster returns a boolean if a field has been set.
func (o *AllocationProperties) HasCluster() bool {
	if o != nil && !IsNil(o.Cluster) {
		return true
	}

	return false
}

// SetCluster gets a reference to the given string and assigns it to the Cluster field.
func (o *AllocationProperties) SetCluster(v string) {
	o.Cluster = &v
}

// GetNode returns the Node field value if set, zero value otherwise.
func (o *AllocationProperties) GetNode() string {
	if o == nil || IsNil(o.Node) {
		var ret string
		return ret
	}
	return *o.Node
}

// GetNodeOk returns a tuple with the Node field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AllocationProperties) GetNodeOk() (*string, bool) {
	if o == nil || IsNil(o.Node) {
		return nil, false
	}
	return o.Node, true
}

// HasNode returns a boolean if a field has been set.
func (o *AllocationProperties) HasNode() bool {
	if o != nil && !IsNil(o.Node) {
		return true
	}

	return false
}

// SetNode gets a reference to the given string and assigns it to the Node field.
func (o *AllocationProperties) SetNode(v string) {
	o.Node = &v
}

// GetController returns the Controller field value if set, zero value otherwise.
func (o *AllocationProperties) GetController() string {
	if o == nil || IsNil(o.Controller) {
		var ret string
		return ret
	}
	return *o.Controller
}

// GetControllerOk returns a tuple with the Controller field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AllocationProperties) GetControllerOk() (*string, bool) {
	if o == nil || IsNil(o.Controller) {
		return nil, false
	}
	return o.Controller, true
}

// HasController returns a boolean if a field has been set.
func (o *AllocationProperties) HasController() bool {
	if o != nil && !IsNil(o.Controller) {
		return true
	}

	return false
}

// SetController gets a reference to the given string and assigns it to the Controller field.
func (o *AllocationProperties) SetController(v string) {
	o.Controller = &v
}

// GetControllerKind returns the ControllerKind field value if set, zero value otherwise.
func (o *AllocationProperties) GetControllerKind() string {
	if o == nil || IsNil(o.ControllerKind) {
		var ret string
		return ret
	}
	return *o.ControllerKind
}

// GetControllerKindOk returns a tuple with the ControllerKind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AllocationProperties) GetControllerKindOk() (*string, bool) {
	if o == nil || IsNil(o.ControllerKind) {
		return nil, false
	}
	return o.ControllerKind, true
}

// HasControllerKind returns a boolean if a field has been set.
func (o *AllocationProperties) HasControllerKind() bool {
	if o != nil && !IsNil(o.ControllerKind) {
		return true
	}

	return false
}

// SetControllerKind gets a reference to the given string and assigns it to the ControllerKind field.
func (o *AllocationProperties) SetControllerKind(v string) {
	o.ControllerKind = &v
}

// GetNamespace returns the Namespace field value if set, zero value otherwise.
func (o *AllocationProperties) GetNamespace() string {
	if o == nil || IsNil(o.Namespace) {
		var ret string
		return ret
	}
	return *o.Namespace
}

// GetNamespaceOk returns a tuple with the Namespace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AllocationProperties) GetNamespaceOk() (*string, bool) {
	if o == nil || IsNil(o.Namespace) {
		return nil, false
	}
	return o.Namespace, true
}

// HasNamespace returns a boolean if a field has been set.
func (o *AllocationProperties) HasNamespace() bool {
	if o != nil && !IsNil(o.Namespace) {
		return true
	}

	return false
}

// SetNamespace gets a reference to the given string and assigns it to the Namespace field.
func (o *AllocationProperties) SetNamespace(v string) {
	o.Namespace = &v
}

// GetPod returns the Pod field value if set, zero value otherwise.
func (o *AllocationProperties) GetPod() string {
	if o == nil || IsNil(o.Pod) {
		var ret string
		return ret
	}
	return *o.Pod
}

// GetPodOk returns a tuple with the Pod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AllocationProperties) GetPodOk() (*string, bool) {
	if o == nil || IsNil(o.Pod) {
		return nil, false
	}
	return o.Pod, true
}

// HasPod returns a boolean if a field has been set.
func (o *AllocationProperties) HasPod() bool {
	if o != nil && !IsNil(o.Pod) {
		return true
	}

	return false
}

// SetPod gets a reference to the given string and assigns it to the Pod field.
func (o *AllocationProperties) SetPod(v string) {
	o.Pod = &v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *AllocationProperties) GetLabels() map[string]string {
	if o == nil || IsNil(o.Labels) {
		var ret map[string]string
		return ret
	}
	return *o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AllocationProperties) GetLabelsOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Labels) {
		return nil, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *AllocationProperties) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]string and assigns it to the Labels field.
func (o *AllocationProperties) SetLabels(v map[string]string) {
	o.Labels = &v
}

// GetProviderID returns the ProviderID field value if set, zero value otherwise.
func (o *AllocationProperties) GetProviderID() string {
	if o == nil || IsNil(o.ProviderID) {
		var ret string
		return ret
	}
	return *o.ProviderID
}

// GetProviderIDOk returns a tuple with the ProviderID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AllocationProperties) GetProviderIDOk() (*string, bool) {
	if o == nil || IsNil(o.ProviderID) {
		return nil, false
	}
	return o.ProviderID, true
}

// HasProviderID returns a boolean if a field has been set.
func (o *AllocationProperties) HasProviderID() bool {
	if o != nil && !IsNil(o.ProviderID) {
		return true
	}

	return false
}

// SetProviderID gets a reference to the given string and assigns it to the ProviderID field.
func (o *AllocationProperties) SetProviderID(v string) {
	o.ProviderID = &v
}

func (o AllocationProperties) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AllocationProperties) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Cluster) {
		toSerialize["cluster"] = o.Cluster
	}
	if !IsNil(o.Node) {
		toSerialize["node"] = o.Node
	}
	if !IsNil(o.Controller) {
		toSerialize["controller"] = o.Controller
	}
	if !IsNil(o.ControllerKind) {
		toSerialize["controllerKind"] = o.ControllerKind
	}
	if !IsNil(o.Namespace) {
		toSerialize["namespace"] = o.Namespace
	}
	if !IsNil(o.Pod) {
		toSerialize["pod"] = o.Pod
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	if !IsNil(o.ProviderID) {
		toSerialize["providerID"] = o.ProviderID
	}
	return toSerialize, nil
}

type NullableAllocationProperties struct {
	value *AllocationProperties
	isSet bool
}

func (v NullableAllocationProperties) Get() *AllocationProperties {
	return v.value
}

func (v *NullableAllocationProperties) Set(val *AllocationProperties) {
	v.value = val
	v.isSet = true
}

func (v NullableAllocationProperties) IsSet() bool {
	return v.isSet
}

func (v *NullableAllocationProperties) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAllocationProperties(val *AllocationProperties) *NullableAllocationProperties {
	return &NullableAllocationProperties{value: val, isSet: true}
}

func (v NullableAllocationProperties) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAllocationProperties) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
