/*
Cost API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the AllocationSetRange type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AllocationSetRange{}

// AllocationSetRange struct for AllocationSetRange
type AllocationSetRange struct {
	Data []map[string]Allocation `json:"data,omitempty"`
}

// NewAllocationSetRange instantiates a new AllocationSetRange object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAllocationSetRange() *AllocationSetRange {
	this := AllocationSetRange{}
	return &this
}

// NewAllocationSetRangeWithDefaults instantiates a new AllocationSetRange object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAllocationSetRangeWithDefaults() *AllocationSetRange {
	this := AllocationSetRange{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *AllocationSetRange) GetData() []map[string]Allocation {
	if o == nil || IsNil(o.Data) {
		var ret []map[string]Allocation
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AllocationSetRange) GetDataOk() ([]map[string]Allocation, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *AllocationSetRange) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []map[string]Allocation and assigns it to the Data field.
func (o *AllocationSetRange) SetData(v []map[string]Allocation) {
	o.Data = v
}

func (o AllocationSetRange) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AllocationSetRange) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableAllocationSetRange struct {
	value *AllocationSetRange
	isSet bool
}

func (v NullableAllocationSetRange) Get() *AllocationSetRange {
	return v.value
}

func (v *NullableAllocationSetRange) Set(val *AllocationSetRange) {
	v.value = val
	v.isSet = true
}

func (v NullableAllocationSetRange) IsSet() bool {
	return v.isSet
}

func (v *NullableAllocationSetRange) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAllocationSetRange(val *AllocationSetRange) *NullableAllocationSetRange {
	return &NullableAllocationSetRange{value: val, isSet: true}
}

func (v NullableAllocationSetRange) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAllocationSetRange) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
