/*
Cost API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the Allocation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Allocation{}

// Allocation struct for Allocation
type Allocation struct {
	Name                  *string               `json:"name,omitempty"`
	Properties            *AllocationProperties `json:"properties,omitempty"`
	Start                 *time.Time            `json:"start,omitempty"`
	End                   *time.Time            `json:"end,omitempty"`
	CpuCoreRequestAverage *float32              `json:"cpuCoreRequestAverage,omitempty"`
	CpuCoreUsageAverage   *float32              `json:"cpuCoreUsageAverage,omitempty"`
	RamByteRequestAverage *float32              `json:"ramByteRequestAverage,omitempty"`
	RamByteUsageAverage   *float32              `json:"ramByteUsageAverage,omitempty"`
	Cost                  *float32              `json:"cost,omitempty"`
	CostRatio             *float32              `json:"costRatio,omitempty"`
	CustomCost            *float32              `json:"customCost,omitempty"`
}

// NewAllocation instantiates a new Allocation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAllocation() *Allocation {
	this := Allocation{}
	return &this
}

// NewAllocationWithDefaults instantiates a new Allocation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAllocationWithDefaults() *Allocation {
	this := Allocation{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *Allocation) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Allocation) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *Allocation) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *Allocation) SetName(v string) {
	o.Name = &v
}

// GetProperties returns the Properties field value if set, zero value otherwise.
func (o *Allocation) GetProperties() AllocationProperties {
	if o == nil || IsNil(o.Properties) {
		var ret AllocationProperties
		return ret
	}
	return *o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Allocation) GetPropertiesOk() (*AllocationProperties, bool) {
	if o == nil || IsNil(o.Properties) {
		return nil, false
	}
	return o.Properties, true
}

// HasProperties returns a boolean if a field has been set.
func (o *Allocation) HasProperties() bool {
	if o != nil && !IsNil(o.Properties) {
		return true
	}

	return false
}

// SetProperties gets a reference to the given AllocationProperties and assigns it to the Properties field.
func (o *Allocation) SetProperties(v AllocationProperties) {
	o.Properties = &v
}

// GetStart returns the Start field value if set, zero value otherwise.
func (o *Allocation) GetStart() time.Time {
	if o == nil || IsNil(o.Start) {
		var ret time.Time
		return ret
	}
	return *o.Start
}

// GetStartOk returns a tuple with the Start field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Allocation) GetStartOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Start) {
		return nil, false
	}
	return o.Start, true
}

// HasStart returns a boolean if a field has been set.
func (o *Allocation) HasStart() bool {
	if o != nil && !IsNil(o.Start) {
		return true
	}

	return false
}

// SetStart gets a reference to the given time.Time and assigns it to the Start field.
func (o *Allocation) SetStart(v time.Time) {
	o.Start = &v
}

// GetEnd returns the End field value if set, zero value otherwise.
func (o *Allocation) GetEnd() time.Time {
	if o == nil || IsNil(o.End) {
		var ret time.Time
		return ret
	}
	return *o.End
}

// GetEndOk returns a tuple with the End field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Allocation) GetEndOk() (*time.Time, bool) {
	if o == nil || IsNil(o.End) {
		return nil, false
	}
	return o.End, true
}

// HasEnd returns a boolean if a field has been set.
func (o *Allocation) HasEnd() bool {
	if o != nil && !IsNil(o.End) {
		return true
	}

	return false
}

// SetEnd gets a reference to the given time.Time and assigns it to the End field.
func (o *Allocation) SetEnd(v time.Time) {
	o.End = &v
}

// GetCpuCoreRequestAverage returns the CpuCoreRequestAverage field value if set, zero value otherwise.
func (o *Allocation) GetCpuCoreRequestAverage() float32 {
	if o == nil || IsNil(o.CpuCoreRequestAverage) {
		var ret float32
		return ret
	}
	return *o.CpuCoreRequestAverage
}

// GetCpuCoreRequestAverageOk returns a tuple with the CpuCoreRequestAverage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Allocation) GetCpuCoreRequestAverageOk() (*float32, bool) {
	if o == nil || IsNil(o.CpuCoreRequestAverage) {
		return nil, false
	}
	return o.CpuCoreRequestAverage, true
}

// HasCpuCoreRequestAverage returns a boolean if a field has been set.
func (o *Allocation) HasCpuCoreRequestAverage() bool {
	if o != nil && !IsNil(o.CpuCoreRequestAverage) {
		return true
	}

	return false
}

// SetCpuCoreRequestAverage gets a reference to the given float32 and assigns it to the CpuCoreRequestAverage field.
func (o *Allocation) SetCpuCoreRequestAverage(v float32) {
	o.CpuCoreRequestAverage = &v
}

// GetCpuCoreUsageAverage returns the CpuCoreUsageAverage field value if set, zero value otherwise.
func (o *Allocation) GetCpuCoreUsageAverage() float32 {
	if o == nil || IsNil(o.CpuCoreUsageAverage) {
		var ret float32
		return ret
	}
	return *o.CpuCoreUsageAverage
}

// GetCpuCoreUsageAverageOk returns a tuple with the CpuCoreUsageAverage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Allocation) GetCpuCoreUsageAverageOk() (*float32, bool) {
	if o == nil || IsNil(o.CpuCoreUsageAverage) {
		return nil, false
	}
	return o.CpuCoreUsageAverage, true
}

// HasCpuCoreUsageAverage returns a boolean if a field has been set.
func (o *Allocation) HasCpuCoreUsageAverage() bool {
	if o != nil && !IsNil(o.CpuCoreUsageAverage) {
		return true
	}

	return false
}

// SetCpuCoreUsageAverage gets a reference to the given float32 and assigns it to the CpuCoreUsageAverage field.
func (o *Allocation) SetCpuCoreUsageAverage(v float32) {
	o.CpuCoreUsageAverage = &v
}

// GetRamByteRequestAverage returns the RamByteRequestAverage field value if set, zero value otherwise.
func (o *Allocation) GetRamByteRequestAverage() float32 {
	if o == nil || IsNil(o.RamByteRequestAverage) {
		var ret float32
		return ret
	}
	return *o.RamByteRequestAverage
}

// GetRamByteRequestAverageOk returns a tuple with the RamByteRequestAverage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Allocation) GetRamByteRequestAverageOk() (*float32, bool) {
	if o == nil || IsNil(o.RamByteRequestAverage) {
		return nil, false
	}
	return o.RamByteRequestAverage, true
}

// HasRamByteRequestAverage returns a boolean if a field has been set.
func (o *Allocation) HasRamByteRequestAverage() bool {
	if o != nil && !IsNil(o.RamByteRequestAverage) {
		return true
	}

	return false
}

// SetRamByteRequestAverage gets a reference to the given float32 and assigns it to the RamByteRequestAverage field.
func (o *Allocation) SetRamByteRequestAverage(v float32) {
	o.RamByteRequestAverage = &v
}

// GetRamByteUsageAverage returns the RamByteUsageAverage field value if set, zero value otherwise.
func (o *Allocation) GetRamByteUsageAverage() float32 {
	if o == nil || IsNil(o.RamByteUsageAverage) {
		var ret float32
		return ret
	}
	return *o.RamByteUsageAverage
}

// GetRamByteUsageAverageOk returns a tuple with the RamByteUsageAverage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Allocation) GetRamByteUsageAverageOk() (*float32, bool) {
	if o == nil || IsNil(o.RamByteUsageAverage) {
		return nil, false
	}
	return o.RamByteUsageAverage, true
}

// HasRamByteUsageAverage returns a boolean if a field has been set.
func (o *Allocation) HasRamByteUsageAverage() bool {
	if o != nil && !IsNil(o.RamByteUsageAverage) {
		return true
	}

	return false
}

// SetRamByteUsageAverage gets a reference to the given float32 and assigns it to the RamByteUsageAverage field.
func (o *Allocation) SetRamByteUsageAverage(v float32) {
	o.RamByteUsageAverage = &v
}

// GetCost returns the Cost field value if set, zero value otherwise.
func (o *Allocation) GetCost() float32 {
	if o == nil || IsNil(o.Cost) {
		var ret float32
		return ret
	}
	return *o.Cost
}

// GetCostOk returns a tuple with the Cost field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Allocation) GetCostOk() (*float32, bool) {
	if o == nil || IsNil(o.Cost) {
		return nil, false
	}
	return o.Cost, true
}

// HasCost returns a boolean if a field has been set.
func (o *Allocation) HasCost() bool {
	if o != nil && !IsNil(o.Cost) {
		return true
	}

	return false
}

// SetCost gets a reference to the given float32 and assigns it to the Cost field.
func (o *Allocation) SetCost(v float32) {
	o.Cost = &v
}

// GetCostRatio returns the CostRatio field value if set, zero value otherwise.
func (o *Allocation) GetCostRatio() float32 {
	if o == nil || IsNil(o.CostRatio) {
		var ret float32
		return ret
	}
	return *o.CostRatio
}

// GetCostRatioOk returns a tuple with the CostRatio field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Allocation) GetCostRatioOk() (*float32, bool) {
	if o == nil || IsNil(o.CostRatio) {
		return nil, false
	}
	return o.CostRatio, true
}

// HasCostRatio returns a boolean if a field has been set.
func (o *Allocation) HasCostRatio() bool {
	if o != nil && !IsNil(o.CostRatio) {
		return true
	}

	return false
}

// SetCostRatio gets a reference to the given float32 and assigns it to the CostRatio field.
func (o *Allocation) SetCostRatio(v float32) {
	o.CostRatio = &v
}

// GetCustomCost returns the CustomCost field value if set, zero value otherwise.
func (o *Allocation) GetCustomCost() float32 {
	if o == nil || IsNil(o.CustomCost) {
		var ret float32
		return ret
	}
	return *o.CustomCost
}

// GetCustomCostOk returns a tuple with the CustomCost field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Allocation) GetCustomCostOk() (*float32, bool) {
	if o == nil || IsNil(o.CustomCost) {
		return nil, false
	}
	return o.CustomCost, true
}

// HasCustomCost returns a boolean if a field has been set.
func (o *Allocation) HasCustomCost() bool {
	if o != nil && !IsNil(o.CustomCost) {
		return true
	}

	return false
}

// SetCustomCost gets a reference to the given float32 and assigns it to the CustomCost field.
func (o *Allocation) SetCustomCost(v float32) {
	o.CustomCost = &v
}

func (o Allocation) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Allocation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Properties) {
		toSerialize["properties"] = o.Properties
	}
	if !IsNil(o.Start) {
		toSerialize["start"] = o.Start
	}
	if !IsNil(o.End) {
		toSerialize["end"] = o.End
	}
	if !IsNil(o.CpuCoreRequestAverage) {
		toSerialize["cpuCoreRequestAverage"] = o.CpuCoreRequestAverage
	}
	if !IsNil(o.CpuCoreUsageAverage) {
		toSerialize["cpuCoreUsageAverage"] = o.CpuCoreUsageAverage
	}
	if !IsNil(o.RamByteRequestAverage) {
		toSerialize["ramByteRequestAverage"] = o.RamByteRequestAverage
	}
	if !IsNil(o.RamByteUsageAverage) {
		toSerialize["ramByteUsageAverage"] = o.RamByteUsageAverage
	}
	if !IsNil(o.Cost) {
		toSerialize["cost"] = o.Cost
	}
	if !IsNil(o.CostRatio) {
		toSerialize["costRatio"] = o.CostRatio
	}
	if !IsNil(o.CustomCost) {
		toSerialize["customCost"] = o.CustomCost
	}
	return toSerialize, nil
}

type NullableAllocation struct {
	value *Allocation
	isSet bool
}

func (v NullableAllocation) Get() *Allocation {
	return v.value
}

func (v *NullableAllocation) Set(val *Allocation) {
	v.value = val
	v.isSet = true
}

func (v NullableAllocation) IsSet() bool {
	return v.isSet
}

func (v *NullableAllocation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAllocation(val *Allocation) *NullableAllocation {
	return &NullableAllocation{value: val, isSet: true}
}

func (v NullableAllocation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAllocation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
