/*
 * Cost API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiCallback;
import org.openapitools.client.ApiClient;
import org.openapitools.client.ApiException;
import org.openapitools.client.ApiResponse;
import org.openapitools.client.Configuration;
import org.openapitools.client.Pair;
import org.openapitools.client.ProgressRequestBody;
import org.openapitools.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import org.openapitools.client.model.AllocationSetRange;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class DefaultApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public DefaultApi() {
        this(Configuration.getDefaultApiClient());
    }

    public DefaultApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for getAllocation
     * @param window The time range to be queried. (required)
     * @param filter The filter options for workloads. (optional)
     * @param step The interval that is used to split the time range. (optional)
     * @param aggregate The aggregate options for the returned results from different dimensions. (optional)
     * @param idle Specifies whether to display or process idle costs. (optional, default to true)
     * @param shareIdle Specifies whether to allocate idle costs to each resource. (optional, default to false)
     * @param shareSplit The idle cost allocation policy. (optional, default to weighted)
     * @param idleByNode Specifies whether to aggregate idle costs of each node. This parameter takes effect only if you set the aggregate parameter to node and the shareIdle parameter to false. (optional, default to false)
     * @param format The format that is used to export costs. (optional, default to json)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad request </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getAllocationCall(@javax.annotation.Nonnull String window, @javax.annotation.Nullable String filter, @javax.annotation.Nullable String step, @javax.annotation.Nullable String aggregate, @javax.annotation.Nullable Boolean idle, @javax.annotation.Nullable Boolean shareIdle, @javax.annotation.Nullable String shareSplit, @javax.annotation.Nullable Boolean idleByNode, @javax.annotation.Nullable String format, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v2/allocation";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (window != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("window", window));
        }

        if (filter != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("filter", filter));
        }

        if (step != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("step", step));
        }

        if (aggregate != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("aggregate", aggregate));
        }

        if (idle != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("idle", idle));
        }

        if (shareIdle != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("shareIdle", shareIdle));
        }

        if (shareSplit != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("shareSplit", shareSplit));
        }

        if (idleByNode != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("idleByNode", idleByNode));
        }

        if (format != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("format", format));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getAllocationValidateBeforeCall(@javax.annotation.Nonnull String window, @javax.annotation.Nullable String filter, @javax.annotation.Nullable String step, @javax.annotation.Nullable String aggregate, @javax.annotation.Nullable Boolean idle, @javax.annotation.Nullable Boolean shareIdle, @javax.annotation.Nullable String shareSplit, @javax.annotation.Nullable Boolean idleByNode, @javax.annotation.Nullable String format, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'window' is set
        if (window == null) {
            throw new ApiException("Missing the required parameter 'window' when calling getAllocation(Async)");
        }

        return getAllocationCall(window, filter, step, aggregate, idle, shareIdle, shareSplit, idleByNode, format, _callback);

    }

    /**
     * Compute allocation
     * 
     * @param window The time range to be queried. (required)
     * @param filter The filter options for workloads. (optional)
     * @param step The interval that is used to split the time range. (optional)
     * @param aggregate The aggregate options for the returned results from different dimensions. (optional)
     * @param idle Specifies whether to display or process idle costs. (optional, default to true)
     * @param shareIdle Specifies whether to allocate idle costs to each resource. (optional, default to false)
     * @param shareSplit The idle cost allocation policy. (optional, default to weighted)
     * @param idleByNode Specifies whether to aggregate idle costs of each node. This parameter takes effect only if you set the aggregate parameter to node and the shareIdle parameter to false. (optional, default to false)
     * @param format The format that is used to export costs. (optional, default to json)
     * @return AllocationSetRange
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad request </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error </td><td>  -  </td></tr>
     </table>
     */
    public AllocationSetRange getAllocation(@javax.annotation.Nonnull String window, @javax.annotation.Nullable String filter, @javax.annotation.Nullable String step, @javax.annotation.Nullable String aggregate, @javax.annotation.Nullable Boolean idle, @javax.annotation.Nullable Boolean shareIdle, @javax.annotation.Nullable String shareSplit, @javax.annotation.Nullable Boolean idleByNode, @javax.annotation.Nullable String format) throws ApiException {
        ApiResponse<AllocationSetRange> localVarResp = getAllocationWithHttpInfo(window, filter, step, aggregate, idle, shareIdle, shareSplit, idleByNode, format);
        return localVarResp.getData();
    }

    /**
     * Compute allocation
     * 
     * @param window The time range to be queried. (required)
     * @param filter The filter options for workloads. (optional)
     * @param step The interval that is used to split the time range. (optional)
     * @param aggregate The aggregate options for the returned results from different dimensions. (optional)
     * @param idle Specifies whether to display or process idle costs. (optional, default to true)
     * @param shareIdle Specifies whether to allocate idle costs to each resource. (optional, default to false)
     * @param shareSplit The idle cost allocation policy. (optional, default to weighted)
     * @param idleByNode Specifies whether to aggregate idle costs of each node. This parameter takes effect only if you set the aggregate parameter to node and the shareIdle parameter to false. (optional, default to false)
     * @param format The format that is used to export costs. (optional, default to json)
     * @return ApiResponse&lt;AllocationSetRange&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad request </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<AllocationSetRange> getAllocationWithHttpInfo(@javax.annotation.Nonnull String window, @javax.annotation.Nullable String filter, @javax.annotation.Nullable String step, @javax.annotation.Nullable String aggregate, @javax.annotation.Nullable Boolean idle, @javax.annotation.Nullable Boolean shareIdle, @javax.annotation.Nullable String shareSplit, @javax.annotation.Nullable Boolean idleByNode, @javax.annotation.Nullable String format) throws ApiException {
        okhttp3.Call localVarCall = getAllocationValidateBeforeCall(window, filter, step, aggregate, idle, shareIdle, shareSplit, idleByNode, format, null);
        Type localVarReturnType = new TypeToken<AllocationSetRange>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Compute allocation (asynchronously)
     * 
     * @param window The time range to be queried. (required)
     * @param filter The filter options for workloads. (optional)
     * @param step The interval that is used to split the time range. (optional)
     * @param aggregate The aggregate options for the returned results from different dimensions. (optional)
     * @param idle Specifies whether to display or process idle costs. (optional, default to true)
     * @param shareIdle Specifies whether to allocate idle costs to each resource. (optional, default to false)
     * @param shareSplit The idle cost allocation policy. (optional, default to weighted)
     * @param idleByNode Specifies whether to aggregate idle costs of each node. This parameter takes effect only if you set the aggregate parameter to node and the shareIdle parameter to false. (optional, default to false)
     * @param format The format that is used to export costs. (optional, default to json)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad request </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getAllocationAsync(@javax.annotation.Nonnull String window, @javax.annotation.Nullable String filter, @javax.annotation.Nullable String step, @javax.annotation.Nullable String aggregate, @javax.annotation.Nullable Boolean idle, @javax.annotation.Nullable Boolean shareIdle, @javax.annotation.Nullable String shareSplit, @javax.annotation.Nullable Boolean idleByNode, @javax.annotation.Nullable String format, final ApiCallback<AllocationSetRange> _callback) throws ApiException {

        okhttp3.Call localVarCall = getAllocationValidateBeforeCall(window, filter, step, aggregate, idle, shareIdle, shareSplit, idleByNode, format, _callback);
        Type localVarReturnType = new TypeToken<AllocationSetRange>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getCost
     * @param window The time range to be queried. (required)
     * @param filter The filter options for workloads. (optional)
     * @param step The interval that is used to split the time range. (optional)
     * @param aggregate The aggregate options for the returned results from different dimensions. (optional)
     * @param idle Specifies whether to display or process idle costs. (optional, default to true)
     * @param shareIdle Specifies whether to allocate idle costs to each resource. (optional, default to false)
     * @param shareSplit The idle cost allocation policy. (optional, default to weighted)
     * @param idleByNode Specifies whether to aggregate idle costs of each node. This parameter takes effect only if you set the aggregate parameter to node and the shareIdle parameter to false. (optional, default to false)
     * @param format The format that is used to export costs. (optional, default to json)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad request </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getCostCall(@javax.annotation.Nonnull String window, @javax.annotation.Nullable String filter, @javax.annotation.Nullable String step, @javax.annotation.Nullable String aggregate, @javax.annotation.Nullable Boolean idle, @javax.annotation.Nullable Boolean shareIdle, @javax.annotation.Nullable String shareSplit, @javax.annotation.Nullable Boolean idleByNode, @javax.annotation.Nullable String format, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v2/cost";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (window != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("window", window));
        }

        if (filter != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("filter", filter));
        }

        if (step != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("step", step));
        }

        if (aggregate != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("aggregate", aggregate));
        }

        if (idle != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("idle", idle));
        }

        if (shareIdle != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("shareIdle", shareIdle));
        }

        if (shareSplit != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("shareSplit", shareSplit));
        }

        if (idleByNode != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("idleByNode", idleByNode));
        }

        if (format != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("format", format));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getCostValidateBeforeCall(@javax.annotation.Nonnull String window, @javax.annotation.Nullable String filter, @javax.annotation.Nullable String step, @javax.annotation.Nullable String aggregate, @javax.annotation.Nullable Boolean idle, @javax.annotation.Nullable Boolean shareIdle, @javax.annotation.Nullable String shareSplit, @javax.annotation.Nullable Boolean idleByNode, @javax.annotation.Nullable String format, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'window' is set
        if (window == null) {
            throw new ApiException("Missing the required parameter 'window' when calling getCost(Async)");
        }

        return getCostCall(window, filter, step, aggregate, idle, shareIdle, shareSplit, idleByNode, format, _callback);

    }

    /**
     * Get estimated cost
     * 
     * @param window The time range to be queried. (required)
     * @param filter The filter options for workloads. (optional)
     * @param step The interval that is used to split the time range. (optional)
     * @param aggregate The aggregate options for the returned results from different dimensions. (optional)
     * @param idle Specifies whether to display or process idle costs. (optional, default to true)
     * @param shareIdle Specifies whether to allocate idle costs to each resource. (optional, default to false)
     * @param shareSplit The idle cost allocation policy. (optional, default to weighted)
     * @param idleByNode Specifies whether to aggregate idle costs of each node. This parameter takes effect only if you set the aggregate parameter to node and the shareIdle parameter to false. (optional, default to false)
     * @param format The format that is used to export costs. (optional, default to json)
     * @return AllocationSetRange
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad request </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error </td><td>  -  </td></tr>
     </table>
     */
    public AllocationSetRange getCost(@javax.annotation.Nonnull String window, @javax.annotation.Nullable String filter, @javax.annotation.Nullable String step, @javax.annotation.Nullable String aggregate, @javax.annotation.Nullable Boolean idle, @javax.annotation.Nullable Boolean shareIdle, @javax.annotation.Nullable String shareSplit, @javax.annotation.Nullable Boolean idleByNode, @javax.annotation.Nullable String format) throws ApiException {
        ApiResponse<AllocationSetRange> localVarResp = getCostWithHttpInfo(window, filter, step, aggregate, idle, shareIdle, shareSplit, idleByNode, format);
        return localVarResp.getData();
    }

    /**
     * Get estimated cost
     * 
     * @param window The time range to be queried. (required)
     * @param filter The filter options for workloads. (optional)
     * @param step The interval that is used to split the time range. (optional)
     * @param aggregate The aggregate options for the returned results from different dimensions. (optional)
     * @param idle Specifies whether to display or process idle costs. (optional, default to true)
     * @param shareIdle Specifies whether to allocate idle costs to each resource. (optional, default to false)
     * @param shareSplit The idle cost allocation policy. (optional, default to weighted)
     * @param idleByNode Specifies whether to aggregate idle costs of each node. This parameter takes effect only if you set the aggregate parameter to node and the shareIdle parameter to false. (optional, default to false)
     * @param format The format that is used to export costs. (optional, default to json)
     * @return ApiResponse&lt;AllocationSetRange&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad request </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<AllocationSetRange> getCostWithHttpInfo(@javax.annotation.Nonnull String window, @javax.annotation.Nullable String filter, @javax.annotation.Nullable String step, @javax.annotation.Nullable String aggregate, @javax.annotation.Nullable Boolean idle, @javax.annotation.Nullable Boolean shareIdle, @javax.annotation.Nullable String shareSplit, @javax.annotation.Nullable Boolean idleByNode, @javax.annotation.Nullable String format) throws ApiException {
        okhttp3.Call localVarCall = getCostValidateBeforeCall(window, filter, step, aggregate, idle, shareIdle, shareSplit, idleByNode, format, null);
        Type localVarReturnType = new TypeToken<AllocationSetRange>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get estimated cost (asynchronously)
     * 
     * @param window The time range to be queried. (required)
     * @param filter The filter options for workloads. (optional)
     * @param step The interval that is used to split the time range. (optional)
     * @param aggregate The aggregate options for the returned results from different dimensions. (optional)
     * @param idle Specifies whether to display or process idle costs. (optional, default to true)
     * @param shareIdle Specifies whether to allocate idle costs to each resource. (optional, default to false)
     * @param shareSplit The idle cost allocation policy. (optional, default to weighted)
     * @param idleByNode Specifies whether to aggregate idle costs of each node. This parameter takes effect only if you set the aggregate parameter to node and the shareIdle parameter to false. (optional, default to false)
     * @param format The format that is used to export costs. (optional, default to json)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad request </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal server error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getCostAsync(@javax.annotation.Nonnull String window, @javax.annotation.Nullable String filter, @javax.annotation.Nullable String step, @javax.annotation.Nullable String aggregate, @javax.annotation.Nullable Boolean idle, @javax.annotation.Nullable Boolean shareIdle, @javax.annotation.Nullable String shareSplit, @javax.annotation.Nullable Boolean idleByNode, @javax.annotation.Nullable String format, final ApiCallback<AllocationSetRange> _callback) throws ApiException {

        okhttp3.Call localVarCall = getCostValidateBeforeCall(window, filter, step, aggregate, idle, shareIdle, shareSplit, idleByNode, format, _callback);
        Type localVarReturnType = new TypeToken<AllocationSetRange>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
