# coding: utf-8

"""
    Cost API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictBool, StrictStr, field_validator
from typing import Optional
from typing_extensions import Annotated
from openapi_client.models.allocation_set_range import AllocationSetRange

from openapi_client.api_client import ApiClient, RequestSerialized
from openapi_client.api_response import ApiResponse
from openapi_client.rest import RESTResponseType


class DefaultApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def get_allocation(
        self,
        window: Annotated[StrictStr, Field(description="The time range to be queried.")],
        filter: Annotated[Optional[StrictStr], Field(description="The filter options for workloads.")] = None,
        step: Annotated[Optional[StrictStr], Field(description="The interval that is used to split the time range.")] = None,
        aggregate: Annotated[Optional[StrictStr], Field(description="The aggregate options for the returned results from different dimensions.")] = None,
        idle: Annotated[Optional[StrictBool], Field(description="Specifies whether to display or process idle costs.")] = None,
        share_idle: Annotated[Optional[StrictBool], Field(description="Specifies whether to allocate idle costs to each resource.")] = None,
        share_split: Annotated[Optional[StrictStr], Field(description="The idle cost allocation policy.")] = None,
        idle_by_node: Annotated[Optional[StrictBool], Field(description="Specifies whether to aggregate idle costs of each node. This parameter takes effect only if you set the aggregate parameter to node and the shareIdle parameter to false.")] = None,
        format: Annotated[Optional[StrictStr], Field(description="The format that is used to export costs.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> AllocationSetRange:
        """Compute allocation


        :param window: The time range to be queried. (required)
        :type window: str
        :param filter: The filter options for workloads.
        :type filter: str
        :param step: The interval that is used to split the time range.
        :type step: str
        :param aggregate: The aggregate options for the returned results from different dimensions.
        :type aggregate: str
        :param idle: Specifies whether to display or process idle costs.
        :type idle: bool
        :param share_idle: Specifies whether to allocate idle costs to each resource.
        :type share_idle: bool
        :param share_split: The idle cost allocation policy.
        :type share_split: str
        :param idle_by_node: Specifies whether to aggregate idle costs of each node. This parameter takes effect only if you set the aggregate parameter to node and the shareIdle parameter to false.
        :type idle_by_node: bool
        :param format: The format that is used to export costs.
        :type format: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_allocation_serialize(
            window=window,
            filter=filter,
            step=step,
            aggregate=aggregate,
            idle=idle,
            share_idle=share_idle,
            share_split=share_split,
            idle_by_node=idle_by_node,
            format=format,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "AllocationSetRange",
            '400': None,
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_allocation_with_http_info(
        self,
        window: Annotated[StrictStr, Field(description="The time range to be queried.")],
        filter: Annotated[Optional[StrictStr], Field(description="The filter options for workloads.")] = None,
        step: Annotated[Optional[StrictStr], Field(description="The interval that is used to split the time range.")] = None,
        aggregate: Annotated[Optional[StrictStr], Field(description="The aggregate options for the returned results from different dimensions.")] = None,
        idle: Annotated[Optional[StrictBool], Field(description="Specifies whether to display or process idle costs.")] = None,
        share_idle: Annotated[Optional[StrictBool], Field(description="Specifies whether to allocate idle costs to each resource.")] = None,
        share_split: Annotated[Optional[StrictStr], Field(description="The idle cost allocation policy.")] = None,
        idle_by_node: Annotated[Optional[StrictBool], Field(description="Specifies whether to aggregate idle costs of each node. This parameter takes effect only if you set the aggregate parameter to node and the shareIdle parameter to false.")] = None,
        format: Annotated[Optional[StrictStr], Field(description="The format that is used to export costs.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[AllocationSetRange]:
        """Compute allocation


        :param window: The time range to be queried. (required)
        :type window: str
        :param filter: The filter options for workloads.
        :type filter: str
        :param step: The interval that is used to split the time range.
        :type step: str
        :param aggregate: The aggregate options for the returned results from different dimensions.
        :type aggregate: str
        :param idle: Specifies whether to display or process idle costs.
        :type idle: bool
        :param share_idle: Specifies whether to allocate idle costs to each resource.
        :type share_idle: bool
        :param share_split: The idle cost allocation policy.
        :type share_split: str
        :param idle_by_node: Specifies whether to aggregate idle costs of each node. This parameter takes effect only if you set the aggregate parameter to node and the shareIdle parameter to false.
        :type idle_by_node: bool
        :param format: The format that is used to export costs.
        :type format: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_allocation_serialize(
            window=window,
            filter=filter,
            step=step,
            aggregate=aggregate,
            idle=idle,
            share_idle=share_idle,
            share_split=share_split,
            idle_by_node=idle_by_node,
            format=format,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "AllocationSetRange",
            '400': None,
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_allocation_without_preload_content(
        self,
        window: Annotated[StrictStr, Field(description="The time range to be queried.")],
        filter: Annotated[Optional[StrictStr], Field(description="The filter options for workloads.")] = None,
        step: Annotated[Optional[StrictStr], Field(description="The interval that is used to split the time range.")] = None,
        aggregate: Annotated[Optional[StrictStr], Field(description="The aggregate options for the returned results from different dimensions.")] = None,
        idle: Annotated[Optional[StrictBool], Field(description="Specifies whether to display or process idle costs.")] = None,
        share_idle: Annotated[Optional[StrictBool], Field(description="Specifies whether to allocate idle costs to each resource.")] = None,
        share_split: Annotated[Optional[StrictStr], Field(description="The idle cost allocation policy.")] = None,
        idle_by_node: Annotated[Optional[StrictBool], Field(description="Specifies whether to aggregate idle costs of each node. This parameter takes effect only if you set the aggregate parameter to node and the shareIdle parameter to false.")] = None,
        format: Annotated[Optional[StrictStr], Field(description="The format that is used to export costs.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Compute allocation


        :param window: The time range to be queried. (required)
        :type window: str
        :param filter: The filter options for workloads.
        :type filter: str
        :param step: The interval that is used to split the time range.
        :type step: str
        :param aggregate: The aggregate options for the returned results from different dimensions.
        :type aggregate: str
        :param idle: Specifies whether to display or process idle costs.
        :type idle: bool
        :param share_idle: Specifies whether to allocate idle costs to each resource.
        :type share_idle: bool
        :param share_split: The idle cost allocation policy.
        :type share_split: str
        :param idle_by_node: Specifies whether to aggregate idle costs of each node. This parameter takes effect only if you set the aggregate parameter to node and the shareIdle parameter to false.
        :type idle_by_node: bool
        :param format: The format that is used to export costs.
        :type format: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_allocation_serialize(
            window=window,
            filter=filter,
            step=step,
            aggregate=aggregate,
            idle=idle,
            share_idle=share_idle,
            share_split=share_split,
            idle_by_node=idle_by_node,
            format=format,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "AllocationSetRange",
            '400': None,
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_allocation_serialize(
        self,
        window,
        filter,
        step,
        aggregate,
        idle,
        share_idle,
        share_split,
        idle_by_node,
        format,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if window is not None:
            
            _query_params.append(('window', window))
            
        if filter is not None:
            
            _query_params.append(('filter', filter))
            
        if step is not None:
            
            _query_params.append(('step', step))
            
        if aggregate is not None:
            
            _query_params.append(('aggregate', aggregate))
            
        if idle is not None:
            
            _query_params.append(('idle', idle))
            
        if share_idle is not None:
            
            _query_params.append(('shareIdle', share_idle))
            
        if share_split is not None:
            
            _query_params.append(('shareSplit', share_split))
            
        if idle_by_node is not None:
            
            _query_params.append(('idleByNode', idle_by_node))
            
        if format is not None:
            
            _query_params.append(('format', format))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/v2/allocation',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def get_cost(
        self,
        window: Annotated[StrictStr, Field(description="The time range to be queried.")],
        filter: Annotated[Optional[StrictStr], Field(description="The filter options for workloads.")] = None,
        step: Annotated[Optional[StrictStr], Field(description="The interval that is used to split the time range.")] = None,
        aggregate: Annotated[Optional[StrictStr], Field(description="The aggregate options for the returned results from different dimensions.")] = None,
        idle: Annotated[Optional[StrictBool], Field(description="Specifies whether to display or process idle costs.")] = None,
        share_idle: Annotated[Optional[StrictBool], Field(description="Specifies whether to allocate idle costs to each resource.")] = None,
        share_split: Annotated[Optional[StrictStr], Field(description="The idle cost allocation policy.")] = None,
        idle_by_node: Annotated[Optional[StrictBool], Field(description="Specifies whether to aggregate idle costs of each node. This parameter takes effect only if you set the aggregate parameter to node and the shareIdle parameter to false.")] = None,
        format: Annotated[Optional[StrictStr], Field(description="The format that is used to export costs.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> AllocationSetRange:
        """Get estimated cost


        :param window: The time range to be queried. (required)
        :type window: str
        :param filter: The filter options for workloads.
        :type filter: str
        :param step: The interval that is used to split the time range.
        :type step: str
        :param aggregate: The aggregate options for the returned results from different dimensions.
        :type aggregate: str
        :param idle: Specifies whether to display or process idle costs.
        :type idle: bool
        :param share_idle: Specifies whether to allocate idle costs to each resource.
        :type share_idle: bool
        :param share_split: The idle cost allocation policy.
        :type share_split: str
        :param idle_by_node: Specifies whether to aggregate idle costs of each node. This parameter takes effect only if you set the aggregate parameter to node and the shareIdle parameter to false.
        :type idle_by_node: bool
        :param format: The format that is used to export costs.
        :type format: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_cost_serialize(
            window=window,
            filter=filter,
            step=step,
            aggregate=aggregate,
            idle=idle,
            share_idle=share_idle,
            share_split=share_split,
            idle_by_node=idle_by_node,
            format=format,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "AllocationSetRange",
            '400': None,
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_cost_with_http_info(
        self,
        window: Annotated[StrictStr, Field(description="The time range to be queried.")],
        filter: Annotated[Optional[StrictStr], Field(description="The filter options for workloads.")] = None,
        step: Annotated[Optional[StrictStr], Field(description="The interval that is used to split the time range.")] = None,
        aggregate: Annotated[Optional[StrictStr], Field(description="The aggregate options for the returned results from different dimensions.")] = None,
        idle: Annotated[Optional[StrictBool], Field(description="Specifies whether to display or process idle costs.")] = None,
        share_idle: Annotated[Optional[StrictBool], Field(description="Specifies whether to allocate idle costs to each resource.")] = None,
        share_split: Annotated[Optional[StrictStr], Field(description="The idle cost allocation policy.")] = None,
        idle_by_node: Annotated[Optional[StrictBool], Field(description="Specifies whether to aggregate idle costs of each node. This parameter takes effect only if you set the aggregate parameter to node and the shareIdle parameter to false.")] = None,
        format: Annotated[Optional[StrictStr], Field(description="The format that is used to export costs.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[AllocationSetRange]:
        """Get estimated cost


        :param window: The time range to be queried. (required)
        :type window: str
        :param filter: The filter options for workloads.
        :type filter: str
        :param step: The interval that is used to split the time range.
        :type step: str
        :param aggregate: The aggregate options for the returned results from different dimensions.
        :type aggregate: str
        :param idle: Specifies whether to display or process idle costs.
        :type idle: bool
        :param share_idle: Specifies whether to allocate idle costs to each resource.
        :type share_idle: bool
        :param share_split: The idle cost allocation policy.
        :type share_split: str
        :param idle_by_node: Specifies whether to aggregate idle costs of each node. This parameter takes effect only if you set the aggregate parameter to node and the shareIdle parameter to false.
        :type idle_by_node: bool
        :param format: The format that is used to export costs.
        :type format: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_cost_serialize(
            window=window,
            filter=filter,
            step=step,
            aggregate=aggregate,
            idle=idle,
            share_idle=share_idle,
            share_split=share_split,
            idle_by_node=idle_by_node,
            format=format,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "AllocationSetRange",
            '400': None,
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_cost_without_preload_content(
        self,
        window: Annotated[StrictStr, Field(description="The time range to be queried.")],
        filter: Annotated[Optional[StrictStr], Field(description="The filter options for workloads.")] = None,
        step: Annotated[Optional[StrictStr], Field(description="The interval that is used to split the time range.")] = None,
        aggregate: Annotated[Optional[StrictStr], Field(description="The aggregate options for the returned results from different dimensions.")] = None,
        idle: Annotated[Optional[StrictBool], Field(description="Specifies whether to display or process idle costs.")] = None,
        share_idle: Annotated[Optional[StrictBool], Field(description="Specifies whether to allocate idle costs to each resource.")] = None,
        share_split: Annotated[Optional[StrictStr], Field(description="The idle cost allocation policy.")] = None,
        idle_by_node: Annotated[Optional[StrictBool], Field(description="Specifies whether to aggregate idle costs of each node. This parameter takes effect only if you set the aggregate parameter to node and the shareIdle parameter to false.")] = None,
        format: Annotated[Optional[StrictStr], Field(description="The format that is used to export costs.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Get estimated cost


        :param window: The time range to be queried. (required)
        :type window: str
        :param filter: The filter options for workloads.
        :type filter: str
        :param step: The interval that is used to split the time range.
        :type step: str
        :param aggregate: The aggregate options for the returned results from different dimensions.
        :type aggregate: str
        :param idle: Specifies whether to display or process idle costs.
        :type idle: bool
        :param share_idle: Specifies whether to allocate idle costs to each resource.
        :type share_idle: bool
        :param share_split: The idle cost allocation policy.
        :type share_split: str
        :param idle_by_node: Specifies whether to aggregate idle costs of each node. This parameter takes effect only if you set the aggregate parameter to node and the shareIdle parameter to false.
        :type idle_by_node: bool
        :param format: The format that is used to export costs.
        :type format: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_cost_serialize(
            window=window,
            filter=filter,
            step=step,
            aggregate=aggregate,
            idle=idle,
            share_idle=share_idle,
            share_split=share_split,
            idle_by_node=idle_by_node,
            format=format,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "AllocationSetRange",
            '400': None,
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_cost_serialize(
        self,
        window,
        filter,
        step,
        aggregate,
        idle,
        share_idle,
        share_split,
        idle_by_node,
        format,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if window is not None:
            
            _query_params.append(('window', window))
            
        if filter is not None:
            
            _query_params.append(('filter', filter))
            
        if step is not None:
            
            _query_params.append(('step', step))
            
        if aggregate is not None:
            
            _query_params.append(('aggregate', aggregate))
            
        if idle is not None:
            
            _query_params.append(('idle', idle))
            
        if share_idle is not None:
            
            _query_params.append(('shareIdle', share_idle))
            
        if share_split is not None:
            
            _query_params.append(('shareSplit', share_split))
            
        if idle_by_node is not None:
            
            _query_params.append(('idleByNode', idle_by_node))
            
        if format is not None:
            
            _query_params.append(('format', format))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/v2/cost',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


